name: Java CI with Maven

on:
  push:
    branches: 
      - "master"
      - "settings"
      - "xml-files"
      - "service"
      - "domain"
      - "controller"
      - "mapper"
  pull_request:
    branches: 
      - "master"
      - "settings"
      - "xml-files"
      - "service"
      - "domain"
      - "controller"
      - "mapper"
      
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: to-do-list
          MYSQL_USER: Beiming
          MYSQL_PASSWORD: 518105309

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until mysql -h 127.0.0.1 -u Beiming -p518105309 -e "SHOW DATABASES;"; do sleep 1; done

      - name: Build with Maven
        run: mvn clean package -Dspring.datasource.url=jdbc:mysql://127.0.0.1:3306/to-do-list

  service-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and run service tests
        if: github.ref == 'refs/heads/service'
        run: mvn -Dtest=org.demo.todo.service.* test

  controller-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and run controller tests
        if: github.ref == 'refs/heads/controller'
        run: mvn -Dtest=org.demo.todo.controller.* test

  mapper-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and run mapper tests
        if: github.ref == 'refs/heads/mapper'
        run: mvn -Dtest=org.demo.todo.mapper.* test

  domain-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and run domain tests
        if: github.ref == 'refs/heads/domain'
        run: mvn -Dtest=org.demo.todo.domain.* test


      - name: Build and run domain tests
        if: github.ref == 'refs/heads/domain'
        run: mvn -Dtest=org.demo.todo.domain.* test

