name: Java CI with Maven

on:
  push:
    branches:
      - main
      - service
      - settings
      - controller
      - mapper
      - domain
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run all tests
        if: github.ref == 'refs/heads/main'
        run: mvn test

      - name: Run service tests
        if: github.ref == 'refs/heads/service'
        run: mvn -Dtest=org.demo.todo.service.* test

      - name: Run database connection tests
        if: github.ref == 'refs/heads/settings'
        run: mvn -Dtest=org.demo.todo.settings.DatabaseConnectionTest test

      - name: Run controller tests
        if: github.ref == 'refs/heads/controller'
        run: mvn -Dtest=org.demo.todo.controller.* test

      - name: Run mapper tests
        if: github.ref == 'refs/heads/mapper'
        run: mvn -Dtest=org.demo.todo.mapper.* test

      - name: Run domain tests
        if: github.ref == 'refs/heads/domain'
        run: mvn -Dtest=org.demo.todo.domain.* test
