name: Java CI with Maven

on:
  push:
    branches:
      - main
      - service
      - settings
      - domain
      - xml-files

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [all, service, settings, domain, xml-files]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin' # Ensure Temurin JDK is used

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build with Maven
      run: |
        if [[ "${{ github.ref_name }}" == "service" ]]; then
          mvn -pl :service -am clean test
        elif [[ "${{ github.ref_name }}" == "settings" ]]; then
          mvn -pl :settings -am clean test
        elif [[ "${{ github.ref_name }}" == "domain" ]]; then
          mvn -pl :domain -am clean test
        elif [[ "${{ github.ref_name }}" == "xml-files" ]]; then
          mvn -pl :xml-files -am clean test
        else
          mvn clean test
        fi

