# Service branch tests
name: Service Branch Tests

on:
  push:
    branches:
      - service

jobs:
  service-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run service tests
        run: mvn -Dtest=org.demo.todo.service.* test
